version: '3'

volumes:
  mongo-volume:

services:
  template_app:
    build: ./app/
    restart: unless-stopped
    env_file: .env
    ports:
      - '8000:8000'
    environment:
      - MONGO_PORT=27017
      - MONGO_DATABASE_URL=mongo_db
    depends_on:
      mongo_db:
        condition: service_started

  test_template:
    build: ./test/
    environment:
      - APP_HOST=template_app
      - APP_PORT=8000
    depends_on:
      template_app:
        condition: service_started

  mongo_db:
    image: mongo:latest
    volumes:
      - mongo-volume:/data/db
      - ./mongo/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
    expose:
      - '27017'
    ports:
      - '27017:27017'
    restart: always
    env_file: 
      - .env
